export enum Actions {
  TOGGLE_QUEUE_DRAWER = "TOGGLE_QUEUE_DRAWER",
  SET_CHART = "SET_CHART",
  SET_PLAYLIST = "SET_PLAYLIST",
  SET_LOADING = "SET_LOADING",
  UNSET_LOADING = "UNSET_LOADING",
  UPDATE_STORE = "UPDATE_STORE",
}
